const state = () => ({
    all: [
        {
            id: 1,
            purpose: 'General-purpose',
            size: 13.3,
            namel: 'Dell XPS 13',
            price: 945.98,
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/Dell_XPS_13.jpg'),
            imageHover: require('../assets/img/Dell_XPS_13.jpg'),
            link: 'https://amzn.to/3tNZwzx',
            ram: 8,
            os: 'Windows 10',
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/alienware_big.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 2,
            size: 15.6,
            purpose: 'Gaming',
            namel: 'Razer Blade 15',
            price: 1599,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: true,
            trending: false,
            company: 'Razer',
            link: 'https://amzn.to/3s1JBgv',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-10750H 6 Core',
            storage: 512,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            image: require('../assets/img/Razer_Blade_15.jpg'),
            bigimage: require('../assets/img/Razer_Blade_15_big.jpg'),
            imageHover: require('../assets/img/Razer_Blade_15.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 3,
            size: 15.6,
            purpose: 'Gaming',
            namel: 'ACER PREDATOR TRITON 500',
            price: 1569.99,
            offer: false,
            offerPrice: 5,
            latest: false,
            bigimage: require('../assets/img/ACER_PREDATOR_TRITON_500_big.jpg'),
            bestSellers: true,
            link: 'https://amzn.to/2Qfynqp',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel i7-10750H',
            storage: 512,
            trending: false,
            company: 'Acer',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            image: require('../assets/img/ACER_PREDATOR_TRITON_500.jpg'),
            imageHover: require('../assets/img/ACER_PREDATOR_TRITON_500.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 4,
            size: 17.3,
            purpose: 'Gaming',
            namel: 'Razer Blade Pro 17',
            price: 2299.99,
            offer: false,
            offerPrice: 7,
            latest: false,
            company: 'Razer',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            bigimage: require('../assets/img/Razer_Blade_Pro_17_big.jpg'),
            link: 'https://amzn.to/3vGo27d',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-10875H 8-Core',
            storage: 512,
            star5: 'fas fa-star-half-alt',
            bestSellers: true,
            trending: false,
            image: require('../assets/img/Razer_Blade_Pro_17.jpg'),
            imageHover: require('../assets/img/Razer_Blade_Pro_17.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 5,
            size: 12.4,
            purpose: 'Gaming',
            namel: 'MSI GS65 STEALTH',
            price: 1231,
            offer: false,
            offerPrice: 7,
            latest: false,
            company: 'MSI',
            bestSellers: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            bigimage: require('../assets/img/MSI_GF63_big.jpg'),
            star3: 'fas fa-star',
            link: 'https://amzn.to/3lvPiRp',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H',
            storage: 512,
            star4: 'fas fa-star',
            star5: ' ',
            trending: false,
            image: require('../assets/img/MSI_GF63.jpg'),
            imageHover: require('../assets/img/MSI_GF63.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 6,
            size: 15.6,
            purpose: 'Gaming',
            namel: 'MSI GP65 Leopard',
            price: 1248.85,
            offer: false,
            offerPrice: 7,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            bigimage: require('../assets/img/MSI_GP65_Leopard_big.jpg'),
            star4: 'fas fa-star',
            link: 'https://amzn.to/3s3I21g',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-10750H',
            storage: 512,
            star5: ' ',
            latest: true,
            company: 'MSI',
            bestSellers: false,
            trending: false,
            image: require('../assets/img/MSI_GP65_Leopard.jpg'),
            imageHover: require('../assets/img/MSI_GP65_Leopard.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 7,
            size: 15.6,
            purpose: 'All-purpose',
            namel: 'Acer Predator Helios 300',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            link: 'https://amzn.to/3eVvDJd',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel i7-10750H',
            storage: 512,
            bigimage: require('../assets/img/Acer_Predator_Helios_300_big.jpg'),
            price: 1249.99,
            offer: false,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            company: 'Acer',
            image: require('../assets/img/Acer_Predator_Helios_300.jpg'),
            imageHover: require('../assets/img/Acer_Predator_Helios_300.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 8,
            size: 17.3,
            purpose: 'All-purpose',
            namel: 'Lenovo Legion Y540',
            price: 1140.00,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            link: 'https://amzn.to/2OQjaMj',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H',
            storage: 1000,
            bigimage: require('../assets/img/Lenovo_Legion_Y540_big.jpg'),
            star4: 'fas fa-star',
            star5: ' ',
            offer: false,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            company: 'Lenovo',
            image: require('../assets/img/Lenovo_Legion_Y540.jpg'),
            imageHover: require('../assets/img/Lenovo_Legion_Y540.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 9,
            size: 14,
            purpose: 'All-purpose',
            namel: 'Asus Rog Zephyrus G14',
            price: 1307,
            offer: false,
            star1: 'fas fa-star',
            bigimage: require('../assets/img/ASUS_ROG_ZEPHYRUS_G14_big.jpg'),
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            link: 'https://amzn.to/3vFlbvc',
            ram: 16,
            os: 'Windows 10',
            processor: '8Core AMD Ryzen 9 4900HS',
            storage: 1000,
            star5: ' ',
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: false,
            company: 'Asus',
            image: require('../assets/img/ASUS_ROG_ZEPHYRUS_G14.jpg'),
            imageHover: require('../assets/img/ASUS_ROG_ZEPHYRUS_G14.jpg'),
            timePeriod: false,
            dateTime: new Date("August 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 10,
            size: 15.6,
            purpose: 'High-performance',
            namel: 'HP Omen 15',
            price: 1139,
            offer: false,
            star1: 'fas fa-star',
            bigimage: require('../assets/img/hp_omen_15_big.jpg'),
            star2: 'fas fa-star',
            link: 'https://amzn.to/2PayxPf',
            ram: 16,
            os: 'Windows 10',
            processor: 'Ryzen 7 4800H 8-Core 2.9GHz',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            offerPrice: 7,
            latest: false,
            company: 'HP',
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_omen_15.jpg'),
            imageHover: require('../assets/img/hp_omen_15.jpg'),
            timePeriod: false,
            trendingProducts: false,
            dateTime: new Date("August 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 11,
            size: 17.3,
            purpose: 'High-performance',
            namel: 'HP Omen 17',
            price: 1349,
            offer: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            bigimage: require('../assets/img/HP_Omen_17_big.jpg'),
            star5: ' ',
            company: 'HP',
            link: 'https://amzn.to/3tO5FM7',
            ram: 12,
            os: 'Windows 10',
            processor: '10th Gen i7-10750H',
            storage: '512',
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_Omen_17.jpg'),
            imageHover: require('../assets/img/HP_Omen_17.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 12,
            size: 15.6,
            purpose: 'High-performance',
            company: 'Dell',
            namel: 'Dell XPS 15',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2Ql8hT7',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7 10th Gen',
            storage: 512,
            star3: 'fas fa-star',
            bigimage: require('../assets/img/Dell_XPS_15_big.jpg'),
            star4: 'fas fa-star',
            star5: '',
            price: 1729,
            offer: false,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_XPS_15.jpg'),
            imageHover: require('../assets/img/Dell_XPS_15.jpg'),
            timePeriod: false,
            dateTime: new Date("April 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 13,
            size: 15,
            purpose: 'All-purpose',
            company: 'Lenovo',
            namel: 'Lenovo Legion Y740',
            link: 'https://amzn.to/30ZeUN4',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H Processor',
            storage: 1000,
            price: 2299,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            bigimage: require('../assets/img/Lenovo_Legion_Y740_big.jpg'),
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/Lenovo_Legion_Y740.jpg'),
            imageHover: require('../assets/img/Lenovo_Legion_Y740.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 14,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Lenovo',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            namel: 'Lenovo ThinkPad P1',
            bigimage: require('../assets/img/Lenovo_ThinkPad_P1_big.jpg'),
            link: 'https://amzn.to/2Qhoh8x',
            ram: 32,
            os: 'Windows 10',
            processor: 'Intel i7-10850H',
            storage: 512,
            price: 1755,
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_ThinkPad_P1.jpg'),
            imageHover: require('../assets/img/Lenovo_ThinkPad_P1.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 15,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'Apple',
            namel: 'Apple MacBook pro 13',
            price: 1799,
            star1: 'fas fa-star',
            bigimage: require('../assets/img/MacBook_pro_big.jpg'),
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            offer: false,
            link: 'https://amzn.to/3lwnqfF',
            ram: 16,
            os: 'MacOS',
            processor: 'Intel Core i5 processor',
            storage: 1000,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/MacBook_pro.jpg'),
            imageHover: require('../assets/img/MacBook_pro.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 16,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Acer',
            namel: 'Acer Swift 3',
            price: 699.99,
            offer: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            offerPrice: 4,
            link: 'https://amzn.to/3c1aJXp',
            ram: 8,
            os: 'Windows 10',
            processor: 'AMD Ryzen 7',
            storage: 512,
            bigimage: require('../assets/img/Acer_Swift_3.jpg'),
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/Acer_Swift_3.jpg'),
            imageHover: require('../assets/img/Acer_Swift_3.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 17,
            size: 17.3,
            purpose: 'Gaming',
            company: 'Dell',
            namel: 'Alienware m17 R3',
            bestSellers: true,
            price: 2230,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3eSr2HK',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-10750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            trending: false,
            bigimage: require('../assets/img/alienware_big.jpg'),
            image: require('../assets/img/alienware.jpg'),
            imageHover: require('../assets/img/alienware.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 18,
            size: 15.6,
            purpose: 'Gaming',
            company: 'Dell',
            namel: 'Alienware M15',
            price: 1799,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3tF4YEr',
            ram: 16,
            os: 'Windows 10',
            processor: 'Core i7-10750H',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/alienware.jpg'),
            imageHover: require('../assets/img/alienware.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/alienware_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 19,
            size: 17.3,
            purpose: 'Gaming',
            company: 'Asus',
            namel: 'Asus Zephyrus S GX701',
            price: 2999.99,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3vEhIx3',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/ASUS_ZEPHYRUS_S_GX701.jpg'),
            imageHover: require('../assets/img/ASUS_ZEPHYRUS_S_GX701.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/ASUS_ZEPHYRUS_S_GX701_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 20,
            size: 16,
            purpose: 'All-purpose',
            company: 'Apple',
            namel: 'Apple MacBook pro 16',
            price: 2199,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38WU3OH',
            ram: 16,
            os: 'MacOS',
            processor: 'Intel Core i7',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Apple_MacBook_pro_13.jpg'),
            imageHover: require('../assets/img/Apple_MacBook_pro_13.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Apple_MacBook_pro_13_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 21,
            size: 15.6,
            purpose: 'High-performance',
            company: 'Asus',
            namel: 'ASUS TUF A15',
            price: 1049,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3eSupOZ',
            ram: 32,
            os: 'Windows 10',
            processor: 'AMD Ryzen 5 4600H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/ASUS_TUF_A15.jpg'),
            imageHover: require('../assets/img/ASUS_TUF_A15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/ASUS_TUF_A15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 22,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Acer',
            namel: 'Acer Aspire 7',
            price: 749.99,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2QmG12v',
            ram: 8,
            os: 'Windows 10',
            processor: 'AMD Ryzen 5 3550H',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Aspire_7.jpg'),
            imageHover: require('../assets/img/Acer_Aspire_7.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Aspire_7_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 23,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'HP',
            namel: 'HP Envy 13 t',
            price: 846,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3r3gRlU',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel i7-1065G7',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_Envy_13t.jpg'),
            imageHover: require('../assets/img/HP_Envy_13t.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_Envy_13t_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 24,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Lenovo',
            namel: 'Lenovo Legion 5i',
            price: 1349,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3f1VYWd',
            ram: 16,
            os: 'Windows 10',
            processor: 'i7-10750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_Legion_5i.jpg'),
            imageHover: require('../assets/img/Lenovo_Legion_5i.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Lenovo_Legion_5i_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 25,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Dell',
            namel: 'Dell G7 15',
            price: 1577.95,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/310KtWy',
            ram: 16,
            os: 'Windows 10 ',
            processor: 'Intel Core i7-10750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_G7_15.jpg'),
            imageHover: require('../assets/img/Dell_G7_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_G7_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 26,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Lenovo',
            namel: 'Lenovo Thinkpad E15',
            price: 1007,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://google.com',
            ram: '',
            os: '',
            processor: '',
            storage: '',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_Thinkpad_E15.jpg'),
            imageHover: require('../assets/img/Lenovo_Thinkpad_E15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Lenovo_Thinkpad_E15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 27,
            size: 15.6,
            purpose: 'Gaming',
            company: 'Dell',
            namel: 'Dell G5 15',
            price: 796,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38Vo6pO',
            ram: 8,
            os: 'Windows 10',
            processor: '10th Gen Core i5-10300H',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_G5_15.jpg'),
            imageHover: require('../assets/img/Dell_G5_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_G5_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 28,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'Apple',
            namel: 'Apple MacBook Air',
            price: 969,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3eXVUH0',
            ram: 8,
            os: 'MacOS',
            processor: '',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Apple_MacBook_Air.jpg'),
            imageHover: require('../assets/img/Apple_MacBook_Air.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Apple_MacBook_Air_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 29,
            size: 14,
            purpose: 'All-purpose',
            company: 'Lenovo',
            namel: 'Lenovo Yoga C940',
            price: 1196.86,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3cHqHVq',
            ram: 12,
            os: 'Windows 10',
            processor: 'Intel Core i7- 1065G7',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_Yoga_C940.jpg'),
            imageHover: require('../assets/img/Lenovo_Yoga_C940.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Lenovo_Yoga_C940_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 56,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Dell',
            namel: 'Dell G3 15',
            price: 839.99,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3eTeoIx',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i5-10300H',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_G3_15.jpg'),
            imageHover: require('../assets/img/Dell_G3_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_G3_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 30,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'Asus',
            namel: 'Asus ZenBook 13 UX333FA',
            price: 1507.96,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/30Wa2rZ',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_Zenbook_13_UX333FA.jpg'),
            imageHover: require('../assets/img/Asus_Zenbook_13_UX333FA.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_Zenbook_13_UX333FA_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 31,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'Google',
            namel: 'Google Pixelbook Go',
            price: 649,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38WWtNs',
            ram: 8,
            os: 'ChromeOS',
            processor: 'Intel',
            storage: 64,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Google_Pixelbook_Go.jpg'),
            imageHover: require('../assets/img/Google_Pixelbook_Go.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Google_Pixelbook_Go_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 32,
            size: 15.9,
            purpose: 'All-purpose',
            company: 'HP',
            namel: 'HP Gaming Pavilion 15-dk0046nr',
            price: 714.99,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3cNee2O',
            ram: 8,
            os: 256,
            processor: 'Intel Core i5-9300H Processor',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_Gaming_Pavilion_15-dk0046nr.jpg'),
            imageHover: require('../assets/img/HP_Gaming_Pavilion_15-dk0046nr.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_Gaming_Pavilion_15-dk0046nr_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 33,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Asus',
            namel: 'Asus VivoBook S15',
            price: 799,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2P9VySs',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-1165G7',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_VivoBook_S15.jpg'),
            imageHover: require('../assets/img/Asus_VivoBook_S15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_VivoBook_S15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 34,
            size: 14,
            purpose: 'All-purpose',
            company: 'Acer',
            namel: 'Acer Spin 3',
            price: 615,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2QnIRnV',
            ram: 8,
            os: 'Windows 10',
            processor: '8th Gen Intel Core i5-8265U',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/acer_spin_3.jpg'),
            imageHover: require('../assets/img/acer_spin_3.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/acer_spin_3_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 35,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Acer',
            namel: 'ACER NITRO 5',
            price: 729,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3s76uyQ',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i5-10300H',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/ACER_NITRO_5.jpg'),
            imageHover: require('../assets/img/ACER_NITRO_5.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/ACER_NITRO_5_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 36,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'HP',
            namel: 'HP Chromebook 15',
            price: 679,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2QdLMzg',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Core i3-8130U',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_chromebook_15.jpg'),
            imageHover: require('../assets/img/hp_chromebook_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/hp_chromebook_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 37,
            size: 14,
            purpose: 'All-purpose',
            company: 'Acer',
            namel: 'Acer chromebook 714',
            ram: 8,
            os: 'ChromeOS',
            processor: 'Intel Core i3-8130U',
            storage: 64,
            price: 629,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3lv1m56',
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Chromebook_714.jpg'),
            imageHover: require('../assets/img/Acer_Chromebook_714.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Chromebook_714_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 38,
            size: 15.6,
            purpose: 'Gaming',
            company: 'MSI',
            namel: 'MSI GF63',
            price: 599,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3qX0NSQ',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i5-9300H',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/MSI_GF63.jpg'),
            imageHover: require('../assets/img/MSI_GF63.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/MSI_GF63_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 39,
            size: 13.5,
            purpose: 'All-purpose',
            company: 'Dell',
            namel: 'Dell Inspiron 14 5000',
            price: 599,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38Y1MvV',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i3-1115G4 Processor',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_Inspiron_14_5000.jpg'),
            imageHover: require('../assets/img/Dell_Inspiron_14_5000.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_Inspiron_14_5000_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 40,
            size: 14,
            purpose: 'All-purpose',
            company: 'Asus',
            namel: 'Asus Chromebook Flip C434',
            price: 487,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38YjBuS',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Core M3-8100Y Processor',
            storage: 64,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_Chromebook_Flip_C434.jpg'),
            imageHover: require('../assets/img/Asus_Chromebook_Flip_C434.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_Chromebook_Flip_C434_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 41,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'HP',
            namel: 'HP 15-dy1036nr',
            price: 539,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3eW3qC1',
            ram: 8,
            os: 'Windows 10',
            processor: '10th Gen Intel Core i5-1035G1',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_15-dy1036nr.jpg'),
            imageHover: require('../assets/img/HP_15-dy1036nr.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_15-dy1036nr_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 42,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Asus',
            namel: 'Asus VivoBook 15',
            price: 444,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3s5m126',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel i3-1005G1',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_VivoBook_S15.jpg'),
            imageHover: require('../assets/img/Asus_VivoBook_S15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_VivoBook_S15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 43,
            size: 14,
            purpose: 'General-purpose',
            company: 'HP',
            namel: 'HP Laptop-14z-dk100',
            price: 587,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3c3XvsA',
            ram: 8,
            os: 'Windows 10',
            processor: '11th Gen Intel Core i5-1135G7 Processor',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            imageHover: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_14_Laptop--df0023cl_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 44,
            size: 12.2,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer Switch 3',
            price: 450,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amazon.com',
            ram: '',
            os: '',
            processor: '',
            storage: '',
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Switch_3.jpg'),
            imageHover: require('../assets/img/Acer_Switch_3.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Switch_3_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 45,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer Aspire 5',
            price: 364,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3c2yZYV',
            ram: 4,
            os: 'Windows 10',
            processor: 'AMD Ryzen 3 3200U',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Aspire_5.jpg'),
            imageHover: require('../assets/img/Acer_Aspire_5.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Aspire_5_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 46,
            size: 14,
            purpose: 'General-purpose',
            company: 'HP',
            namel: 'HP 14-Inch Laptop DF0023CL',
            price: 379,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/30YCs4t',
            ram: 4,
            os: 'Windows 10',
            processor: 'Intel Core i3-8130U',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            imageHover: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_14_Laptop--df0023cl_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 47,
            size: 15,
            purpose: 'General-purpose',
            company: 'HP',
            namel: 'HP 15',
            price: 349,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38T7Eqj',
            ram: 4,
            os: 'Windows 10',
            processor: 'Intel Pentium Gold 6405U',
            storage: 500,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_15.jpg'),
            imageHover: require('../assets/img/hp_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/hp_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 48,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer Chromebook 15',
            price: 349,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38XNISW',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Celeron N3350',
            storage: 32,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Chromebook_714.jpg'),
            imageHover: require('../assets/img/Acer_Chromebook_714.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Chromebook_714_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 49,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Dell',
            namel: 'Dell Inspiron 15 3000',
            price: 329,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3vHe99p',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel 2-Core 4205U Processor',
            storage: 128,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_Inspiron_15.jpg'),
            imageHover: require('../assets/img/Dell_Inspiron_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_Inspiron_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 50,
            size: 14,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer chromebook 314',
            price: 300,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3eTI1cI',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Celeron N4000',
            storage: 64,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Chromebook_314.jpg'),
            imageHover: require('../assets/img/Acer_Chromebook_314.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Chromebook_314_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 51,
            size: 14,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer Swift 1',
            price: 259,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2OHqFVX',
            ram: 4,
            os: 'Windows 10',
            processor: 'Intel N5000 ',
            storage: 64,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Swift_1.jpg'),
            imageHover: require('../assets/img/Acer_Swift_1.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Swift_1_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 52,
            size: 11.6,
            purpose: 'General-purpose',
            company: 'Samsung',
            namel: 'Samsung Chromebook 4',
            price: 241,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/38ZIBll',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Celeron Processor',
            storage: 64,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Samsung_Chromebook_4.jpg'),
            imageHover: require('../assets/img/Samsung_Chromebook_4.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Samsung_Chromebook_4_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 53,
            size: 14.1,
            purpose: 'General-purpose',
            company: 'HP',
            namel: 'HP Chromebook 14',
            price: 279,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3s49M68',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Celeron N4000',
            storage: 32,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_chromebook_14.jpg'),
            imageHover: require('../assets/img/hp_chromebook_14.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/hp_chromebook_14_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 54,
            size: 11.6,
            purpose: 'General-purpose',
            company: 'Samsung',
            namel: 'Samsung Chromebook 3',
            price: 227,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://google.com',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel',
            storage: 16,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Samsung_Chromebook_3.jpg'),
            imageHover: require('../assets/img/Samsung_Chromebook_3.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Samsung_Chromebook_3_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 55,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer Aspire 1',
            price: 249,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3s51smH',
            ram: 4,
            os: 'Windows 10',
            processor: 'Intel Processor N4020',
            storage: 64,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_aspire_1.jpg'),
            imageHover: require('../assets/img/Acer_aspire_1.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_aspire_1_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
    ]
});

export default {
    state
};
