const state = () => ({
    all: [
      {
          id: 'HFBR-4513-4503z-patch-cord',
          purpose: 'General-purpose, Designing, Student',
          size: 13.3,
          namel: 'HFBR 4513/4503Z patch cord',
          gpu: 'Intel UHD Graphics',
          batterylife: 12,
          price: 2.50,
          offer: false,
          offerPrice: 3,
          latest: true,
          bestSellers: false,
          trending: true,
          image: require('../assets/img/Dell_XPS_13.jpg'),
          imageHover: require('../assets/img/Dell_XPS_13.jpg'),
          link: 'https://amzn.to/2R8qKmv',
          ram: 8,
          os: 'Windows 10',
          weight: 2.8,
          processor: '10th Gen Intel i7-10510U Processor',
          storage: '512',
          bigimage: require('../assets/img/alienware_big.jpg'),
          company: 'Dell',
          timePeriod: false,
          star1: 'fas fa-star',
          star2: 'fas fa-star',
          star3: 'fas fa-star',
          star4: 'fas fa-star',
          star5: 'fas fa-star-half-alt',
          dateTime: new Date("December 19, 2020 17:00:00 PDT"),
          description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
      },
        {
            id: 'HFBR-4516z-patch-cord',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'HFBR-4516 patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/HFBR-4516z-duplex-patch-cord.jpg'),
            imageHover: require('../assets/img/HFBR-4516z-duplex-patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/HFBR-4516z-duplex-patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'HFBR4501-4511z',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'HFBR4501/4511z Patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/HFBR-45014511z-orange.jpg'),
            imageHover: require('../assets/img/HFBR-45014511z-orange.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/HFBR-45014511z-orange.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'mrj3bus-duplex',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'MRJ3BUS Duplex',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/MRJ3BUS-Duplex.jpg'),
            imageHover: require('../assets/img/MRJ3BUS-Duplex.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/MRJ3BUS-Duplex.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'hfbr-4532z-patch-cord',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'HFBR 4532z patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/HFBR-4532z-patch-cord.jpg'),
            imageHover: require('../assets/img/HFBR-4532z-patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/HFBR-4532z-patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'sma905-patch-cord',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'sma905 patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/sma905-patch-cord.jpg'),
            imageHover: require('../assets/img/sma905-patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/sma905-patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'hfbr-4501-4511z-patch-cord',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'HFBR-4501/4511z patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/HFBR45014511z-Patch-cord.jpg'),
            imageHover: require('../assets/img/HFBR45014511z-Patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/HFBR45014511z-Patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'st-st-fiber-optic',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'ST-ST Fiber optic patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/Dell_XPS_13.jpg'),
            imageHover: require('../assets/img/Dell_XPS_13.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/alienware_big.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'fc-fc-fiber-optic',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'FC-FC Fiber optic patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/FC-FC-Fiber-optic-patch-cord.jpg'),
            imageHover: require('../assets/img/FC-FC-Fiber-optic-patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/FC-FC-Fiber-optic-patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'hfbr-4533-4531z-patch-cord',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'HFBR 4533/4531z patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HFBR-45334531z-patch-cord.jpg'),
            imageHover: require('../assets/img/HFBR-45334531z-patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/HFBR-45334531z-patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'toslink-audio-fiber-optic-patch-cord',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'Toslink audio fiber optic patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Toslink-audio-fiber-optic-patch-cord.jpg'),
            imageHover: require('../assets/img/Toslink-audio-fiber-optic-patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/Toslink-audio-fiber-optic-patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 'hfbr-4516z-duplex-patch-cord',
            purpose: 'General-purpose, Designing, Student',
            size: 13.3,
            namel: 'HFBR 4516z duplex patch cord',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 210,
            offer: false,
            offerPrice: 3,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HFBR-4516z-duplex-patch-cord.jpg'),
            imageHover: require('../assets/img/HFBR-4516z-duplex-patch-cord.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/HFBR-4516z-duplex-patch-cord.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        }
    ]
});

export default {
    state
};
