const state = () => ({
    all: [
        {
            id: 1,
            purpose: 'General-purpose, Designing',
            size: 13.3,
            namel: 'Dell XPS 13',
            gpu: 'Intel UHD Graphics',
            batterylife: 12,
            price: 1599,
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/Dell_XPS_13.jpg'),
            imageHover: require('../assets/img/Dell_XPS_13.jpg'),
            link: 'https://amzn.to/2R8qKmv',
            ram: 8,
            os: 'Windows 10',
            weight: 2.8,
            processor: '10th Gen Intel i7-10510U Processor',
            storage: '512',
            bigimage: require('../assets/img/alienware_big.jpg'),
            company: 'Dell',
            timePeriod: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: 'One of the best All-purpose laptops right now. Dell XPS 13 delivers a powerful performance. You can count on this Dell machine for any kind of work and you will not be disappointed.'
        },
        {
            id: 2,
            size: 15.6,
            purpose: 'Gaming',
            gpu: 'NVIDIA GeForce RTX 3060',
            batterylife: 6,
            namel: 'Razer Blade 15',
            price: 1699.99,
            offer: false,
            offerPrice: 3,
            latest: false,
            weight: 4.40,
            bestSellers: true,
            trending: false,
            company: 'Razer',
            link: 'https://amzn.to/3p7wBFe',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-10750H 6 Core',
            storage: 512,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            image: require('../assets/img/Razer_Blade_15.jpg'),
            bigimage: require('../assets/img/Razer_Blade_15_big.jpg'),
            imageHover: require('../assets/img/Razer_Blade_15.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 3,
            size: 15.6,
            purpose: 'Gaming',
            gpu: 'NVIDIA GeForce RTX 2070 SUPER',
            batterylife: 4,
            namel: 'ACER PREDATOR TRITON 500',
            price: 1569.99,
            offer: false,
            offerPrice: 5,
            latest: false,
            weight: 4.6,
            bigimage: require('../assets/img/ACER_PREDATOR_TRITON_500_big.jpg'),
            bestSellers: true,
            link: 'https://amzn.to/2Qfynqp',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel i7-10750H',
            storage: 512,
            trending: false,
            company: 'Acer',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            image: require('../assets/img/ACER_PREDATOR_TRITON_500.jpg'),
            imageHover: require('../assets/img/ACER_PREDATOR_TRITON_500.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 4,
            size: 17.3,
            purpose: 'Gaming',
            gpu: 'NVIDIA GeForce RTX 3060',
            batterylife: 4.5,
            namel: 'Razer Blade Pro 17',
            weight: 6.06,
            price: 2299.99,
            offer: false,
            offerPrice: 7,
            latest: false,
            company: 'Razer',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            bigimage: require('../assets/img/Razer_Blade_Pro_17_big.jpg'),
            link: 'https://amzn.to/2S3aqns',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-10875H 8-Core',
            storage: 512,
            star5: 'fas fa-star-half-alt',
            bestSellers: true,
            trending: false,
            image: require('../assets/img/Razer_Blade_Pro_17.jpg'),
            imageHover: require('../assets/img/Razer_Blade_Pro_17.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 5,
            size: 12.4,
            purpose: 'Gaming',
            gpu: 'NVIDIA GeForce GTX 1660 Ti',
            batterylife: 7,
            namel: 'MSI GS65 STEALTH',
            price: 1231,
            offer: false,
            offerPrice: 7,
            weight: 1.88,
            latest: false,
            company: 'MSI',
            bestSellers: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            bigimage: require('../assets/img/MSI_GF63_big.jpg'),
            star3: 'fas fa-star',
            link: 'https://amzn.to/2S1W471',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H',
            storage: 512,
            star4: 'fas fa-star',
            star5: ' ',
            trending: false,
            image: require('../assets/img/MSI_GF63.jpg'),
            imageHover: require('../assets/img/MSI_GF63.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 6,
            size: 15.6,
            purpose: 'Gaming, Designing',
            gpu: 'NVM Express',
            batterylife: 8,
            namel: 'MSI GP65 Leopard',
            price: 1248.85,
            offer: false,
            offerPrice: 7,
            weight: 5.13,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            bigimage: require('../assets/img/MSI_GP65_Leopard_big.jpg'),
            star4: 'fas fa-star',
            link: 'https://amzn.to/3uDX5iS',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-10750H',
            storage: 512,
            star5: ' ',
            latest: true,
            company: 'MSI',
            bestSellers: false,
            trending: false,
            image: require('../assets/img/MSI_GP65_Leopard.jpg'),
            imageHover: require('../assets/img/MSI_GP65_Leopard.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 7,
            size: 15.6,
            purpose: 'All-purpose',
            gpu: 'NVIDIA GeForce RTX 2060',
            batterylife: 3.5,
            namel: 'Acer Predator Helios 300',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            link: 'https://amzn.to/3fWkPJL',
            ram: 16,
            weight: 4.8,
            os: 'Windows 10',
            processor: 'Intel i7-10750H',
            storage: 512,
            bigimage: require('../assets/img/Acer_Predator_Helios_300_big.jpg'),
            price: 1249.99,
            offer: false,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            company: 'Acer',
            image: require('../assets/img/Acer_Predator_Helios_300.jpg'),
            imageHover: require('../assets/img/Acer_Predator_Helios_300.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 8,
            size: 17.3,
            gpu: 'NVIDIA GeForce RTX 2060',
            batterylife: 5,
            purpose: 'All-purpose',
            namel: 'Lenovo Legion Y540',
            price: 1249.00,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            link: 'https://amzn.to/34GJDA1',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H',
            storage: 1000,
            bigimage: require('../assets/img/Lenovo_Legion_Y540_big.jpg'),
            star4: 'fas fa-star',
            star5: ' ',
            weight: 5.73,
            offer: false,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            company: 'Lenovo',
            image: require('../assets/img/Lenovo_Legion_Y540.jpg'),
            imageHover: require('../assets/img/Lenovo_Legion_Y540.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 9,
            size: 14,
            gpu: 'NVIDIA GeForce RTX 2060',
            batterylife: 8,
            purpose: 'All-purpose, Designing',
            namel: 'Asus Rog Zephyrus G14',
            price: 1307,
            offer: false,
            star1: 'fas fa-star',
            bigimage: require('../assets/img/ASUS_ROG_ZEPHYRUS_G14_big.jpg'),
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            link: 'https://amzn.to/3g3pz0l',
            ram: 16,
            weight: 3.5,
            os: 'Windows 10',
            processor: '8Core AMD Ryzen 9 4900HS',
            storage: 1000,
            star5: ' ',
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: false,
            company: 'Asus',
            image: require('../assets/img/ASUS_ROG_ZEPHYRUS_G14.jpg'),
            imageHover: require('../assets/img/ASUS_ROG_ZEPHYRUS_G14.jpg'),
            timePeriod: false,
            dateTime: new Date("August 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 10,
            size: 15.6,
            purpose: 'High-performance',
            namel: 'HP Omen 15',
            gpu: 'NVIDIA GTX 1660 Ti',
            batterylife: 6,
            price: 1139,
            offer: false,
            star1: 'fas fa-star',
            bigimage: require('../assets/img/hp_omen_15_big.jpg'),
            star2: 'fas fa-star',
            link: 'https://amzn.to/3wN6CWh',
            ram: 16,
            weight: 5.4,
            os: 'Windows 10',
            processor: 'Ryzen 7 4800H 8-Core 2.9GHz',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            offerPrice: 7,
            latest: false,
            company: 'HP',
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_omen_15.jpg'),
            imageHover: require('../assets/img/hp_omen_15.jpg'),
            timePeriod: false,
            trendingProducts: false,
            dateTime: new Date("August 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 11,
            size: 17.3,
            purpose: 'High-performance',
            namel: 'HP Omen 17',
            price: 1649,
            offer: false,
            gpu: 'NVIDIA GeForce RTX 2070',
            batterylife: 5,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            bigimage: require('../assets/img/HP_Omen_17_big.jpg'),
            star5: ' ',
            weight: 8.23,
            company: 'HP',
            link: 'https://amzn.to/3uz2zLD',
            ram: 12,
            os: 'Windows 10',
            processor: '10th Gen i7-10750H',
            storage: 512,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_Omen_17.jpg'),
            imageHover: require('../assets/img/HP_Omen_17.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 12,
            size: 15.6,
            purpose: 'High-performance, Designing',
            company: 'Dell',
            gpu: 'Nvidia GeForce GTX 1650 Ti',
            batterylife: 11,
            namel: 'Dell XPS 15',
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3p4XkSY',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7 10th Gen',
            storage: 512,
            star3: 'fas fa-star',
            bigimage: require('../assets/img/Dell_XPS_15_big.jpg'),
            star4: 'fas fa-star',
            star5: '',
            weight: 4.5,
            price: 1729,
            offer: false,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_XPS_15.jpg'),
            imageHover: require('../assets/img/Dell_XPS_15.jpg'),
            timePeriod: false,
            dateTime: new Date("April 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 13,
            size: 15,
            purpose: 'All-purpose',
            company: 'Lenovo',
            gpu: 'NVIDIA GeForce GTX 1660 Ti',
            batterylife: 4,
            namel: 'Lenovo Legion Y740',
            link: 'https://amzn.to/3z0E51B',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H Processor',
            storage: 1000,
            price: 1599,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            weight: 4.8,
            bigimage: require('../assets/img/Lenovo_Legion_Y740_big.jpg'),
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/Lenovo_Legion_Y740.jpg'),
            imageHover: require('../assets/img/Lenovo_Legion_Y740.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 14,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Lenovo',
            gpu: 'NVIDIA Quadro T2000',
            batterylife: 7,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            namel: 'Lenovo ThinkPad P1',
            bigimage: require('../assets/img/Lenovo_ThinkPad_P1_big.jpg'),
            link: 'https://amzn.to/3uCl1Dd',
            ram: 32,
            weight: 4,
            os: 'Windows 10',
            processor: 'Intel i7-10850H',
            storage: 1000,
            price: 2775,
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_ThinkPad_P1.jpg'),
            imageHover: require('../assets/img/Lenovo_ThinkPad_P1.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 15,
            size: 13.3,
            purpose: 'All-purpose, Designing',
            company: 'Apple',
            gpu: 'Intel Iris Plus',
            batterylife: 10,
            namel: 'Apple MacBook pro 13',
            price: 1599,
            star1: 'fas fa-star',
            bigimage: require('../assets/img/MacBook_pro_big.jpg'),
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            offer: false,
            link: 'https://amzn.to/3fBBgvT',
            ram: 16,
            os: 'MacOS',
            weight: 3.08,
            processor: 'Intel Core i5 processor',
            storage: 512,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/MacBook_pro.jpg'),
            imageHover: require('../assets/img/MacBook_pro.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 16,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Acer',
            gpu: 'Radeon',
            batterylife: 7,
            namel: 'Acer Swift 3',
            price: 699.99,
            offer: false,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            offerPrice: 4,
            link: 'https://amzn.to/3vE4M9X',
            ram: 8,
            weight: 2.7,
            os: 'Windows 10',
            processor: 'AMD Ryzen 7',
            storage: 512,
            bigimage: require('../assets/img/Acer_Swift_3.jpg'),
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/Acer_Swift_3.jpg'),
            imageHover: require('../assets/img/Acer_Swift_3.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 17,
            size: 17.3,
            purpose: 'Gaming',
            company: 'Dell',
            gpu: 'NVIDIA GeForce RTX 2070',
            batterylife: 3,
            namel: 'Alienware m17 R3',
            bestSellers: true,
            price: 3399,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3i8PLcq',
            ram: 16,
            weight: 6.54,
            os: 'Windows 10',
            processor: 'Intel Core i7-10750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            trending: false,
            bigimage: require('../assets/img/alienware_big.jpg'),
            image: require('../assets/img/alienware.jpg'),
            imageHover: require('../assets/img/alienware.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 18,
            size: 15.6,
            purpose: 'Gaming',
            company: 'Dell',
            gpu: 'NVIDIA RTX 2060',
            batterylife: 4,
            namel: 'Alienware M15',
            price: 1646,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/34xLWFN',
            ram: 16,
            weight: 4.8,
            os: 'Windows 10',
            processor: 'Core i7-10750H',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/alienware.jpg'),
            imageHover: require('../assets/img/alienware.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/alienware_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 19,
            size: 17.3,
            purpose: 'Gaming',
            company: 'Asus',
            gpu: 'NVIDIA GeForce RTX 2070',
            batterylife: 3.5,
            namel: 'Asus Zephyrus S GX701',
            weight: 5.95,
            price: 2999.99,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3wMR84F',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-9750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/ASUS_ZEPHYRUS_S_GX701.jpg'),
            imageHover: require('../assets/img/ASUS_ZEPHYRUS_S_GX701.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/ASUS_ZEPHYRUS_S_GX701_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 20,
            size: 16,
            purpose: 'All-purpose',
            company: 'Apple',
            gpu: 'Intel UHD Graphics 630',
            batterylife: 9,
            namel: 'Apple MacBook pro 16',
            price: 2549,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3p8QA6y',
            ram: 16,
            weight: 4.3,
            os: 'MacOS',
            processor: 'Intel Core i7',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Apple_MacBook_pro_13.jpg'),
            imageHover: require('../assets/img/Apple_MacBook_pro_13.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Apple_MacBook_pro_13_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 21,
            size: 15.6,
            gpu: 'NVIDIA GeForce GTX 1050',
            batterylife: 4,
            purpose: 'High-performance',
            company: 'Asus',
            namel: 'ASUS TUF A15',
            price: 1049,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3vKNtV2',
            ram: 32,
            os: 'Windows 10',
            processor: 'AMD Ryzen 5 4600H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: 'fas fa-star-half-alt',
            latest: false,
            weight: 5.07,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/ASUS_TUF_A15.jpg'),
            imageHover: require('../assets/img/ASUS_TUF_A15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/ASUS_TUF_A15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 22,
            size: 15.6,
            purpose: 'All-purpose, Gaming',
            company: 'Acer',
            gpu: 'NVIDIA GeForce GTX 1650',
            batterylife: 11,
            namel: 'Acer Aspire 7',
            price: 749.99,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3vDTR0d',
            ram: 8,
            os: 'Windows 10',
            processor: 'AMD Ryzen 5 3550H',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            weight: 4.7,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Aspire_7.jpg'),
            imageHover: require('../assets/img/Acer_Aspire_7.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Aspire_7_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 23,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'HP',
            namel: 'HP Envy 13 t',
            price: 846,
            gpu: 'Intel Iris Plus',
            batterylife: 10,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3uBQvcM',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel i7-1065G7',
            storage: 512,
            weight: 2.8,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_Envy_13t.jpg'),
            imageHover: require('../assets/img/HP_Envy_13t.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_Envy_13t_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 24,
            size: 15.6,
            purpose: 'All-purpose, Gaming',
            company: 'Lenovo',
            namel: 'Lenovo Legion 5i',
            price: 1549,
            offer: false,
            gpu: 'NVIDIA GeForce RTX 2060',
            batterylife: 8,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3ikqU5J',
            ram: 16,
            os: 'Windows 10',
            processor: 'i7-10750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            weight: 5.2,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_Legion_5i.jpg'),
            imageHover: require('../assets/img/Lenovo_Legion_5i.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Lenovo_Legion_5i_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 25,
            size: 15.6,
            purpose: 'All-purpose, Gaming',
            company: 'Dell',
            namel: 'Dell G7 15',
            price: 1577.95,
            gpu: 'NVIDIA GeForce RTX 2070',
            batterylife: 5,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3wMnNHr',
            ram: 16,
            os: 'Windows 10 ',
            processor: 'Intel Core i7-10750H',
            storage: 1000,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            weight: 5.95,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_G7_15.jpg'),
            imageHover: require('../assets/img/Dell_G7_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_G7_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 26,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'Lenovo',
            namel: 'Lenovo Thinkpad E15',
            price: 1007,
            offer: false,
            offerPrice: 4,
            gpu: 'Intel UHD Graphics 620',
            batterylife: 10,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2Om5bh4',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel 10th Quad Core i5-10210U',
            storage: 512,
            weight: 4.1,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_Thinkpad_E15.jpg'),
            imageHover: require('../assets/img/Lenovo_Thinkpad_E15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Lenovo_Thinkpad_E15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 27,
            size: 15.6,
            purpose: 'Gaming',
            company: 'Dell',
            namel: 'Dell G5 15',
            price: 796,
            gpu: 'NVidia GTX 1650 Ti',
            batterylife: 3,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3g1G90f',
            ram: 8,
            weight: 5.95,
            os: 'Windows 10',
            processor: '10th Gen Core i5-10300H',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_G5_15.jpg'),
            imageHover: require('../assets/img/Dell_G5_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_G5_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 28,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'Apple',
            namel: 'Apple MacBook Air',
            price: 969,
            offer: false,
            gpu: 'Apple 8-core',
            batterylife: 12,
            offerPrice: 4,
            weight: 2.79,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3uE2uGG',
            ram: 8,
            os: 'MacOS',
            processor: '',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Apple_MacBook_Air.jpg'),
            imageHover: require('../assets/img/Apple_MacBook_Air.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Apple_MacBook_Air_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 29,
            size: 14,
            purpose: 'All-purpose',
            company: 'Lenovo',
            namel: 'Lenovo Yoga C940',
            price: 1030,
            offer: false,
            gpu: 'Intel Iris Plus',
            batterylife: 4,
            offerPrice: 4,
            weight: 3,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3p8w1qH',
            ram: 12,
            os: 'Windows 10',
            processor: 'Intel Core i7- 1065G7',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_Yoga_C940.jpg'),
            imageHover: require('../assets/img/Lenovo_Yoga_C940.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Lenovo_Yoga_C940_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 56,
            size: 15.6,
            purpose: 'All-purpose, Gaming',
            company: 'Dell',
            namel: 'Dell G3 15',
            price: 839.99,
            offer: false,
            weight: 5.5,
            gpu: 'NVIDIA GeForce GTX 1650 Ti',
            batterylife: 4,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3z0IXDV',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i5-10300H',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_G3_15.jpg'),
            imageHover: require('../assets/img/Dell_G3_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_G3_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 30,
            size: 13.3,
            purpose: 'All-purpose, Designing',
            company: 'Asus',
            namel: 'Asus ZenBook 13 UX333FA',
            price: 1507.96,
            offer: false,
            offerPrice: 4,
            weight: 2.69,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            gpu: 'Intel HD Graphics 620',
            batterylife: 10,
            link: 'https://amzn.to/3vEaokx',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_Zenbook_13_UX333FA.jpg'),
            imageHover: require('../assets/img/Asus_Zenbook_13_UX333FA.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_Zenbook_13_UX333FA_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 31,
            size: 13.3,
            purpose: 'All-purpose',
            company: 'Google',
            namel: 'Google Pixelbook Go',
            price: 649,
            weight: 2.3,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2SOL2SM',
            ram: 8,
            os: 'ChromeOS',
            gpu: 'NA',
            batterylife: 10,
            processor: 'Intel',
            storage: 64,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Google_Pixelbook_Go.jpg'),
            imageHover: require('../assets/img/Google_Pixelbook_Go.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Google_Pixelbook_Go_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 32,
            size: 15.9,
            purpose: 'All-purpose, Gaming',
            company: 'HP',
            namel: 'HP Gaming Pavilion 15-dk0046nr',
            price: 714.99,
            offer: false,
            weight: 4.96,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3fFEZsG',
            ram: 8,
            gpu: 'NVIDIA GeForce GTX 1050',
            batterylife: 8.5,
            os: 'Windows 10',
            processor: 'Intel Core i5-9300H Processor',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_Gaming_Pavilion_15-dk0046nr.jpg'),
            imageHover: require('../assets/img/HP_Gaming_Pavilion_15-dk0046nr.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_Gaming_Pavilion_15-dk0046nr_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 33,
            size: 15.6,
            purpose: 'All-purpose, Designing',
            company: 'Asus',
            namel: 'Asus VivoBook S15',
            price: 879,
            offer: false,
            offerPrice: 4,
            weight: 3.96,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3fAIuAv',
            ram: 16,
            os: 'Windows 10',
            processor: 'Intel Core i7-1165G7',
            storage: 512,
            star3: 'fas fa-star',
            star4: 'fas fa-star',
            star5: ' ',
            gpu: 'Intel Iris Xe Graphics',
            batterylife: 10,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_VivoBook_S15.jpg'),
            imageHover: require('../assets/img/Asus_VivoBook_S15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_VivoBook_S15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 34,
            size: 14,
            purpose: 'All-purpose',
            company: 'Acer',
            namel: 'Acer Spin 3',
            price: 615,
            offer: false,
            offerPrice: 4,
            weight: 3.7,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3fT0yoo',
            ram: 8,
            os: 'Windows 10',
            processor: '8th Gen Intel Core i5-8265U',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            gpu: 'Intel UHD Graphics 620',
            batterylife: 10.5,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/acer_spin_3.jpg'),
            imageHover: require('../assets/img/acer_spin_3.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/acer_spin_3_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 35,
            size: 15.6,
            purpose: 'All-purpose, Gaming',
            company: 'Acer',
            namel: 'ACER NITRO 5',
            price: 729,
            offer: false,
            offerPrice: 4,
            weight: 5.9,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3yTMNyw',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i5-10300H',
            storage: 256,
            gpu: 'NVIDIA GeForce GTX 1650 Ti',
            batterylife: 9,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/ACER_NITRO_5.jpg'),
            imageHover: require('../assets/img/ACER_NITRO_5.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/ACER_NITRO_5_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 36,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'HP',
            namel: 'HP Chromebook 15',
            price: 539,
            offer: false,
            offerPrice: 4,
            weight: 3.96,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3fAsZZc',
            ram: 4,
            os: 'ChromeOS',
            gpu: 'Intel UHD Graphics 620',
            batterylife: 11.5,
            processor: 'Intel Core i3-8130U',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_chromebook_15.jpg'),
            imageHover: require('../assets/img/hp_chromebook_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/hp_chromebook_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 37,
            size: 14,
            purpose: 'All-purpose',
            company: 'Acer',
            namel: 'Acer chromebook 714',
            ram: 8,
            os: 'ChromeOS',
            processor: 'Intel Core i3-8130U',
            storage: 64,
            gpu: 'Intel UHD Graphics 620',
            batterylife: 12,
            price: 629,
            offer: false,
            offerPrice: 4,
            weight: 3.3,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3wL8IG1',
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Chromebook_714.jpg'),
            imageHover: require('../assets/img/Acer_Chromebook_714.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Chromebook_714_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 38,
            size: 15.6,
            purpose: 'Gaming',
            company: 'MSI',
            namel: 'MSI GF63',
            price: 769,
            gpu: 'NVIDIA GeForce GTX 1650',
            batterylife: 3,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3i6CK2Z',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i5-9300H',
            storage: 256,
            weight: 4.1,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/MSI_GF63.jpg'),
            imageHover: require('../assets/img/MSI_GF63.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/MSI_GF63_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 39,
            size: 13.5,
            purpose: 'All-purpose',
            company: 'Dell',
            gpu: 'Intel UHD Graphics',
            batterylife: 8,
            namel: 'Dell Inspiron 14 5000',
            price: 599,
            offer: false,
            offerPrice: 4,
            weight: 4.65,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3yS11jm',
            ram: 8,
            os: 'Windows 10',
            processor: 'Intel Core i3-1115G4 Processor',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_Inspiron_14_5000.jpg'),
            imageHover: require('../assets/img/Dell_Inspiron_14_5000.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_Inspiron_14_5000_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 40,
            size: 14,
            purpose: 'All-purpose',
            company: 'Asus',
            gpu: 'Intel HD Graphics 615',
            batterylife: 10,
            namel: 'Asus Chromebook Flip C434',
            price: 487,
            offer: false,
            offerPrice: 4,
            weight: 3.1,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/34xm5h4',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Core M3-8100Y Processor',
            storage: 64,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_Chromebook_Flip_C434.jpg'),
            imageHover: require('../assets/img/Asus_Chromebook_Flip_C434.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_Chromebook_Flip_C434_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 41,
            size: 15.6,
            purpose: 'All-purpose',
            company: 'HP',
            namel: 'HP 15-dy1036nr',
            price: 658,
            offer: false,
            gpu: 'Intel UHD Graphics',
            batterylife: 10,
            offerPrice: 4,
            weight: 3.7,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2RaLomb',
            ram: 8,
            os: 'Windows 10',
            processor: '10th Gen Intel Core i5-1035G1',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_15-dy1036nr.jpg'),
            imageHover: require('../assets/img/HP_15-dy1036nr.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_15-dy1036nr_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 42,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Asus',
            namel: 'Asus VivoBook 15',
            price: 444,
            offer: false,
            offerPrice: 4,
            gpu: 'Intel UHD Graphics',
            batterylife: 5,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3vGmTMu',
            ram: 8,
            weight: 3.5,
            os: 'Windows 10',
            processor: 'Intel i3-1005G1',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Asus_VivoBook_S15.jpg'),
            imageHover: require('../assets/img/Asus_VivoBook_S15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Asus_VivoBook_S15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 43,
            size: 14,
            purpose: 'General-purpose',
            company: 'HP',
            gpu: 'Intel Iris',
            batterylife: 7,
            namel: 'HP Laptop-14z-dk100',
            price: 587,
            offer: false,
            offerPrice: 4,
            weight: 3.3,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3uyJF7T',
            ram: 8,
            os: 'Windows 10',
            processor: '11th Gen Intel Core i5-1135G7 Processor',
            storage: 256,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            imageHover: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_14_Laptop--df0023cl_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 44,
            size: 12.2,
            purpose: 'General-purpose',
            company: 'Acer',
            gpu: 'Intel UHD Graphics',
            batterylife: 8,
            namel: 'Acer Switch 3',
            price: 450,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3vIPWPM',
            ram: 4,
            weight: 3.3,
            os: 'Windows 10',
            processor: '',
            storage: '',
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Switch_3.jpg'),
            imageHover: require('../assets/img/Acer_Switch_3.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Switch_3_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 45,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Acer',
            gpu: 'AMD Radeon Vega 3',
            batterylife: 7,
            namel: 'Acer Aspire 5',
            price: 364,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3yQWPQJ',
            ram: 4,
            os: 'Windows 10',
            processor: 'AMD Ryzen 3 3200U',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            weight: 4.8,
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Aspire_5.jpg'),
            imageHover: require('../assets/img/Acer_Aspire_5.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Aspire_5_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 46,
            size: 14,
            purpose: 'General-purpose',
            company: 'HP',
            namel: 'HP 14-Inch Laptop DF0023CL',
            price: 379,
            offer: false,
            gpu: 'Intel UHD Graphics 620',
            batterylife: 6,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3fE8zi5',
            ram: 4,
            weight: 3.1,
            os: 'Windows 10',
            processor: 'Intel Core i3-8130U',
            storage: 128,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            imageHover: require('../assets/img/HP_14_Laptop--df0023cl.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_14_Laptop--df0023cl_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 47,
            size: 15,
            purpose: 'General-purpose',
            company: 'HP',
            namel: 'HP 15',
            price: 573,
            gpu: 'NA',
            batterylife: 10,
            weight: 4.4,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2RaMJJJ',
            ram: 4,
            os: 'Windows 10',
            processor: 'Intel Pentium Gold 6405U',
            storage: 500,
            star3: 'fas fa-star',
            star4: 'fas fa-star-half-alt',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_15.jpg'),
            imageHover: require('../assets/img/hp_15_big.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/hp_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 48,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Acer',
            gpu: 'Intel Celeron N3350',
            batterylife: 12,
            namel: 'Acer Chromebook 15',
            price: 349,
            weight: 4.85,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3uEZGcc',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Celeron N3350',
            storage: 32,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Chromebook_714.jpg'),
            imageHover: require('../assets/img/Acer_Chromebook_714.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Chromebook_714_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 49,
            size: 15.6,
            purpose: 'General-purpose, Designing',
            company: 'Dell',
            gpu: 'Intel HD Graphics 610',
            batterylife: 2.5,
            namel: 'Dell Inspiron 15 3000',
            price: 469,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3uDj3Tg',
            ram: 8,
            weight: 5.26,
            os: 'Windows 10',
            processor: 'Intel 2-Core 4205U Processor',
            storage: 256,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Dell_Inspiron_15.jpg'),
            imageHover: require('../assets/img/Dell_Inspiron_15.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Dell_Inspiron_15_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 50,
            size: 14,
            purpose: 'General-purpose',
            company: 'Acer',
            gpu: 'Intel UHD Graphics 600',
            batterylife: 12.5,
            namel: 'Acer chromebook 314',
            price: 300,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3fDkIE1',
            ram: 4,
            os: 'ChromeOS',
            weight: 3.75,
            processor: 'Intel Celeron N4000',
            storage: 64,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Chromebook_314.jpg'),
            imageHover: require('../assets/img/Acer_Chromebook_314.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Chromebook_314_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 51,
            size: 14,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer Swift 1',
            price: 407,
            gpu: 'Intel UHD Graphics',
            batterylife: 13,
            offer: false,
            weight: 4.2,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/34B4mp6',
            ram: 4,
            os: 'Windows 10',
            processor: 'Intel N5000 ',
            storage: 64,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_Swift_1.jpg'),
            imageHover: require('../assets/img/Acer_Swift_1.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_Swift_1_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 52,
            size: 11.6,
            purpose: 'General-purpose',
            company: 'Samsung',
            gpu: 'NA',
            batterylife: 12,
            namel: 'Samsung Chromebook 4',
            price: 241,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3fIG5E5',
            ram: 4,
            os: 'ChromeOS',
            processor: 'Intel Celeron Processor',
            storage: 64,
            weight: 3.7,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Samsung_Chromebook_4.jpg'),
            imageHover: require('../assets/img/Samsung_Chromebook_4.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Samsung_Chromebook_4_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 53,
            size: 14.1,
            purpose: 'General-purpose',
            company: 'HP',
            gpu: 'NA',
            batterylife: 13,
            namel: 'HP Chromebook 14',
            price: 279,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3p5H6Jk',
            ram: 4,
            weight: 4.07,
            os: 'ChromeOS',
            processor: 'Intel Celeron N4000',
            storage: 32,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/hp_chromebook_14.jpg'),
            imageHover: require('../assets/img/hp_chromebook_14.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/hp_chromebook_14_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 54,
            size: 11.6,
            purpose: 'General-purpose',
            company: 'Samsung',
            gpu: 'Intel HD Graphics 400',
            batterylife: 10,
            namel: 'Samsung Chromebook 3',
            price: 227,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/3p6AxGc',
            ram: 4,
            weight: 2.53,
            os: 'ChromeOS',
            processor: 'Intel',
            storage: 16,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Samsung_Chromebook_3.jpg'),
            imageHover: require('../assets/img/Samsung_Chromebook_3.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Samsung_Chromebook_3_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 55,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'Acer',
            namel: 'Acer Aspire 1',
            price: 249,
            gpu: 'Intel UHD Graphics 600',
            batterylife: 10,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/34A5zNj',
            ram: 4,
            weight: 2.78,
            os: 'Windows 10',
            processor: 'Intel Processor N4020',
            storage: 64,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Acer_aspire_1.jpg'),
            imageHover: require('../assets/img/Acer_aspire_1.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Acer_aspire_1_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 57,
            size: 15.6,
            purpose: 'General-purpose',
            company: 'HP',
            gpu: 'Intel UHD Graphics 600',
            batterylife: 11,
            namel: 'HP Stream 11',
            price: 268,
            offer: false,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/2To2gGE',
            ram: 4,
            weight: 2.82,
            os: 'Windows 10',
            processor: 'Intel Celeron N4000',
            storage: 32,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/HP_Stream_11.jpg'),
            imageHover: require('../assets/img/HP_Stream_11.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/HP_Stream_11_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
        {
            id: 58,
            size: 14,
            purpose: 'General-purpose',
            company: 'Lenovo',
            namel: 'Lenovo IdeaPad 1',
            price: 329,
            offer: false,
            gpu: 'Intel UHD Graphics 605',
            batterylife: 8,
            offerPrice: 4,
            star1: 'fas fa-star',
            star2: 'fas fa-star',
            link: 'https://amzn.to/34xg04p',
            ram: 4,
            weight: 3.08,
            os: 'Windows 10',
            processor: 'Intel Pentium Silver N5030',
            storage: 128,
            star3: 'fas fa-star',
            star4: ' ',
            star5: ' ',
            latest: false,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/Lenovo_Ideapad_1.jpg'),
            imageHover: require('../assets/img/Lenovo_Ideapad_1.jpg'),
            timePeriod: false,
            bigimage: require('../assets/img/Lenovo_Ideapad_1_big.jpg'),
            dateTime: new Date("December 19, 2020 17:00:00 PDT"),
            description: ''
        },
    ]
});

export default {
    state
};
